MXC_CSI_CAMERA: select VIDEOBUF2_DMA_CONTIG
MXC_CSI_CAMERA links to the following functions provided by
VIDEOBUF2_DMA_CONTIG, so select it explicitely to prevent
link errors:

ERROR: "vb2_dma_contig_cleanup_ctx" [drivers/media/platform/mxc/subdev/mx6s_capture.ko] undefined!
ERROR: "vb2_dma_contig_memops" [drivers/media/platform/mxc/subdev/mx6s_capture.ko] undefined!
ERROR: "vb2_dma_contig_init_ctx" [drivers/media/platform/mxc/subdev/mx6s_capture.ko] undefined!

Signed-off-by: Max Krummenacher <max.krummenacher@toradex.com>
Acked-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
(cherry picked from commit a3ff407abf1fc9ad2072a94ab301850c837a17ce)
(cherry picked from commit 502376a5735998dfceb09ba8d2889df5dcfa5b58)